flag_management:
  individual_flags:
    - name: dotnet
      carryforward: true
      paths:
        - coverage/dotnet-coverage-unit
        - coverage/dotnet-coverage-integration
    - name: nodejs
      carryforward: true
      paths: 
        - coverage/nodejs-coverage
