flag_management:
  individual_flags:
    - name: dotnet-unit
      carryforward: true
      paths:
        - services/Skyra.UnitTests/TestResults/
    - name: dotnet-it
      carryforward: true
      paths:
        - services/Skyra.IntegrationTests/TestResults/
    - name: nodejs-unit
      carryforward: true
      paths:
        - coverage/
