project_id: '434340'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'
commit_message: '[skip ci]'
files:
  - source: /src/languages/en-US/**/*.json
    translation: /src/languages/%locale%/**/%original_file_name%
