version: "2.4"
services:
  pokedex:
    container_name: pokedex
    image: favware/graphql-pokemon:master
    restart: always
    ports:
      - "4000:8080"
  postgres:
    container_name: pgsql
    image: skyrabot/postgres:master
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  lavalink:
    network_mode: host
    container_name: lavalink
    image: skyrabot/lavalink:master
    restart: always
    ports:
      - "2333:2333"
  saelem:
    container_name: saelem
    image: skyrabot/saelem:master
    restart: always
    ports:
      - "8284:8080"
  influx:
    container_name: influxdb
    image: quay.io/influxdb/influxdb:2.0.0-beta
    restart: always
    volumes:
      - influx-data:/var/lib/influxdb2
    ports:
      - "8285:9999"
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt

volumes:
  postgres-data:
    external: true
  influx-data:
    external: true
#   grafana-data:
#     external: true
