version: "2.4"
services:
  pokedex:
    image: favware/graphql-pokemon:latest
  postgres:
    build: ./postgres
    image: skyrabot/postgres:latest
  lavalink:
    image: skyrabot/lavalink:latest
    build: ./lavalink
