version: '2.4'
services:
  grpc:
    image: skyrabot/grpc:latest
    container_name: 'skyra-grpc'
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=skyra
    networks:
      - skyra
    ports:
      - '8291:80'
  pokedex:
    container_name: pokedex
    image: favware/graphql-pokemon:latest
    restart: always
    networks:
      - skyra
    ports:
      - '4000:8288'
  postgres:
    container_name: pgsql
    image: skyrabot/postgres:latest
    restart: always
    networks:
      - skyra
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  lavalink:
    container_name: lavalink
    image: skyrabot/lavalink:latest
    restart: always
    depends_on:
      - redis
    networks:
      - skyra
    ports:
      - '2333:2333'
  saelem:
    container_name: saelem
    image: skyrabot/saelem:latest
    restart: always
    depends_on:
      - redis
    environment:
      SAELEM_REDIS_HOST: redis
      SAELEM_REDIS_PORT: 8287
      SAELEM_REDIS_PASSWORD: redis
      SAELEM_REDIS_DATABASE: 0
      PORT: 8284
    ports:
      - '8284:8284'
    networks:
      - skyra
  influx:
    container_name: influxdb
    image: quay.io/influxdb/influxdb:v2.0.3
    restart: always
    volumes:
      - influx-data:/var/lib/influxdb2
    ports:
      - '8285:8086'
    networks:
      - skyra
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '8287:8287'
    networks:
      - skyra
    command: redis-server --port 8287 --requirepass redis
  hasteserver:
    container_name: hasteserver
    image: skyrabot/haste-server:latest
    restart: always
    depends_on:
      - redis
    ports:
      - '8290:8290'
    networks:
      - skyra
    environment:
      PORT: 8290
      STORAGE_TYPE: redis
      STORAGE_HOST: host.docker.internal
      STORAGE_PORT: 8287
      STORAGE_PASSWORD: redis
      STORAGE_DB: 2
      STORAGE_EXPIRE_SECONDS: 21600
  outflux:
    container_name: outflux
    image: skyrabot/outflux:latest
    restart: always
    depends_on:
      - influx
    networks:
      - skyra
    environment:
      INFLUX_BASE_URL: 'http://host.docker.internal:8285'
    ports:
      - '8286:8286'

volumes:
  postgres-data:
    external: true
  influx-data:
    external: true

networks:
  skyra:
