name: Auto Rename Crowdin PRs

on:
  pull_request:
    branches:
      - main

jobs:
  rename_crowdin_prs:
    name: Auto Rename Crowdin PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2
      - name: Install GitHub CLI
        run: |
          curl -sL \
              $(curl -sL \
                  -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
                  -X POST \
                  --data '{"query":"query { repository(owner: \"cli\", name: \"cli\") { releases(last: 1) { nodes { releaseAssets(first: 20) { nodes { downloadUrl name }}}}}}"}' "https://api.github.com/graphql" |
                  jq -cr '.data.repository.releases.nodes[0].releaseAssets.nodes[]? | select(.name | contains("linux_amd64.tar.gz")).downloadUrl') |
              tar -xz --wildcards "*gh" && mv gh*linux_amd64/bin/gh . && rm -r gh_*linux_amd64
      - name: Change PR title
        if: (github.event.pull_request.title == 'New Crowdin updates' && github.event.pull_request.user.login == 'NM-EEA-Y' && github.event.pull_request.head.ref == 'i18n/crowdin')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "./gh pr edit ${{ github.event.pull_request.number }} --title 'feat(crowdin): update localization files'"
