name: Continuous Delivery

on:
  push:
    branches:
      - main
    paths:
      - 'services/**'
      - 'assets/protos/*'
      - 'docker/docker-compose.yml'
      - 'docker/playwithdocker-grpc-stack.yml'
      - '.github/workflows/continuous-delivery.yml'

jobs:
  Publish:
    name: Publish image to container registries
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.2.0
      - name: Login to DockerHub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Protofiles Docker image
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./assets/protos
          push: true
          tags: ghcr.io/skyra-project/grpc-protofiles:latest
      - name: Build and push GRPC Docker image
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          context: ./services
          tags: |
            skyrabot/grpc:latest
            ghcr.io/skyra-project/grpc:latest
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2.4.2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: skyrabot/grpc
          readme-filepath: ./services/Skyra.Grpc/README.md
          short-description: GRPC Microservice to interact with Skyra Database
